# Put document versions here for every major or minor release
# Every TOML list item contains the following properties:
# - "version"   - text that appears in versions menu
# - "dirpath"   - directory name (relative to contentDir) where documentation
#                 for given version resides
# - "url"       - url for link in version menu. May be absolute URL.
# - "latestTag" - docker image tag for the latest patch version. Must be changed
#                 on every patch release of respective branch

[[versions]]
    version = "10.5"
    dirpath = "latest"
    url = "/latest/"
[[versions]]
    version = "10.4"
    dirpath = "10.4"
    url = "/10.4/"
[[versions]]
    version = "10.3"
    dirpath = "10.3"
    url = "/10.3/"
[[versions]]
    version = "10.2"
    dirpath = "10.2"
    url = "/10.2/"
[[versions]]
    version = "Older"
    url = "https://sdk.gooddata.com/gooddata-ui/versions.html"
