name: check

on:
  pull_request:

concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-validate-stage:
    permissions:
      id-token: write
      contents: read
      pull-requests: read
    name: build-validate-stage
    uses: ./.github/workflows/rw-rush-build-basic-checks.yml
    secrets: inherit

  ready-to-merge:
    runs-on:
      group: infra1-runners-arc
      labels: runners-small
    if: always()
    needs:
      - build-validate-stage

    steps:
      - name: Check if needed jobs succeeded
        uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: ${{ toJSON(needs) }}
          jobs: ${{ toJSON(needs) }}
