name: gate
on:
  merge_group:
    types:
      - checks_requested
jobs:
  e2e-stage:
    permissions:
      id-token: write
      contents: read
      pull-requests: read
    name: e2e-stage
    uses: ./.github/workflows/rw-rush-build-e2e-tests.yml
    secrets: inherit

  ready-to-merge:
    runs-on:
      group: infra1-runners-arc
      labels: runners-small
    if: always()
    needs:
      - e2e-stage
    steps:
      - name: Check if needed jobs succeeded
        uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: ${{ toJSON(needs) }}
          jobs: ${{ toJSON(needs) }}
