name: Doc ~ Netlify Deploy
on:
  workflow_dispatch:

jobs:
  netlify-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Hugo Build
        uses: ./.github/actions/hugo-build-versioned-action
        with:
          base-url: https://www.gooddata.com/docs/gooddata-ui
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy -d docs/public --prod
        env:
          NETLIFY_SITE_ID: 8a177d37-8476-44eb-a92a-29eaa19a4a26
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
