# (C) 2024 GoodData Corporation

name: Release ~ Publish alpha
on:
    workflow_dispatch:
jobs:
    publish-alpha:
        uses: ./.github/workflows/rw-publish-version.yml
        permissions:
            contents: write
        secrets: inherit
        with:
            source-branch: "master"
            release-tag: "alpha"
