# (C) 2024 GoodData Corporation

name: Pull request ~ Prerelease
on:
  push:    
    branches:
      - master
      - release

jobs:
  get-label-from-pr:
    runs-on: [ubuntu-latest]
    outputs:
        should-prerelease: ${{ steps.needs-prerelease.outputs.result }}
        brach-name: ${{ steps.extract-branch.outputs.branch }}
    steps:
      - uses: actions/github-script@v7
        id: needs-prerelease
        with:
          script: |
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0]?.labels?.some((it)=>it.name==='publish pre-release');            
          result-encoding: string
      - name: Extract branch name
        env:
          CURRENT_REF: ${{ github.event.ref }}
        id: extract-branch
        shell: bash
        run: echo "branch=${CURRENT_REF#refs/heads/}" >> $GITHUB_OUTPUT
        

  publish-pre-release:
    needs: [get-label-from-pr]
    name: Publish pre-release
    if: ${{ needs.get-label-from-pr.outputs.should-prerelease == 'true' }}        
    uses: ./.github/workflows/rw-publish-prerelease.yml
    secrets: inherit
    permissions:
      contents: write
      id-token: write
    with:      
      source-branch:  ${{ needs.get-label-from-pr.outputs.brach-name }}
