# (C) 2024 GoodData Corporation

name: Pull request ~ Prerelease
on:
  pull_request:
    types: [closed]
    branches:
      - master
      - release

jobs:
  publish-pre-release:
    name: Publish pre-release
    if: >
        github.event.pull_request.merged == true &&
        contains(github.event.pull_request.labels.*.name, 'publish pre-release')
    uses: ./.github/workflows/rw-publish-prerelase.yml
    permissions:
      contents: write
      id-token: write
    with:      
      source-branch: ${{ github.event.pull_request.base.ref }}
